name: kilo
description: A basic console text editor written in Dart.
version: 0.2.1
author: Tim Sneath <timsneath@google.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_console: ^1.2.0

dev_dependencies:
  pedantic: ^1.8.0+1
